before_build:
  - dotnet restore

build_script:
  - dotnet build --no-restore
  - dotnet pack BerTlv\BerTlv.csproj --no-build -o ../dist

test_script:
  - dotnet test --no-build

deploy: off

artifacts:
  - path: 'dist\*.nupkg'
